### PR TITLE
Added shell test for `cfbs remove`

### PR DESCRIPTION
**Pull request by larsewi**
Ticket: None
Changelog: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

### CODE REVIEW

**Review by olehermanse — CHANGES_REQUESTED** [review]
Please see my review in your other PR:

https://github.com/cfengine/cfbs/pull/63

**Review by craigcomstock — COMMENTED** [review]
yes, move the `set` s to `all.sh` and good to go.

**Comment by olehermanse** [comment]
@craigcomstock I didn't mean the set's, I just meant that all.sh has the list of all tests to run, these new tests need to be included :)

**Review by craigcomstock — APPROVED** [review]

**Review by craigcomstock — APPROVED** [review]

**Comment by craigcomstock** [comment]
> @craigcomstock I didn't mean the set's, I just meant that all.sh has the list of all tests to run, these new tests need to be included :)

Sure. Makes sense. :+1:

**Pull request merged**
