### PR TITLE
Fixed status command for locally added policy files

### PR DESCRIPTION
**Pull request by olehermanse**
Format matches that of cfbs build;

```
$ cfbs status
Name:        Example
Description: Example description
File:        cfbs.json

Modules:
001 masterfiles @ 5c7dc5b43088e259a94de4e5a9f17c0ce9781a0f (Downloaded)
002 autorun     @ c3b7329b240cf7ad062a0a64ee8b607af2cb912a (Downloaded)
003 ./test.cf   @ local                                    (Copied)
```

### CODE REVIEW

**Review by nickanderson — CHANGES_REQUESTED** [review]
Maybe I didn't patch correctly, but I still get an error after simple cfbs init and then cfbs status.

```
[root@hub cfbs]# rm cfbs.json 
rm: remove regular file ‘cfbs.json’? yes
[root@hub cfbs]# cfbs init
Initialized - edit name and description cfbs.json
To add your first module, type: cfbs add masterfiles
[root@hub cfbs]# cfbs status
Name:        Example
Description: Example description
File:        cfbs.json

Modules:
Traceback (most recent call last):
  File "/usr/local/bin/cfbs", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cfbs/main.py", line 130, in main
    return commands.status_command()
  File "/usr/local/lib/python3.6/site-packages/cfbs/commands.py", line 138, in status_command
    max_length = longest_module_name()
  File "/usr/local/lib/python3.6/site-packages/cfbs/commands.py", line 784, in longest_module_name
    return max((len(m["name"]) for m in get_definition()["build"]))
ValueError: max() arg is an empty sequence

```

**Comment by olehermanse** [comment]
@nickanderson Why would you do that? ;) That's not what this ticket is about.

**Review by larsewi — APPROVED** [review]
ACK. The issue @nickanderson stated, is another bug and should be another ticket.

**Comment by olehermanse** [comment]
@nickanderson @larsewi [Fixed](https://github.com/cfengine/cfbs/pull/71/commits/900019b56e88dbfc126920c499cbe74323909057)

Merry xmas!

**Review by larsewi — APPROVED** [review]
ACK

**Comment by nickanderson** [comment]
> @nickanderson Why would you do that? ;) That's not what this ticket is about.

It's not? I thought it was in the example I posted https://tracker.mender.io/browse/CFE-3850

As to why ...

Well, i am trying to find all the cfbs tickle spots

**Comment by olehermanse** [comment]
@nickanderson all good, of course. The issue Lars first pointed out in slack was after adding a local policy file

**Pull request merged**
